### PR TITLE
dockerised version

### PR DESCRIPTION
**Pull request by mosajjal**
#  #

## 🗣 Description ##

Simplifies the build by providing a Dockerfile and docker-compose

## 💭 Motivation and context ##

Not sure if this is something that's in line with the project. I removed a lot of prompts and init scripts in favor of relying on env variables to provide all the configurations. 

## 🧪 Testing ##

My initial tests using docker-compose lead to an instance being created seamlessly.

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Comment by damionmounts** [comment]
This is most certainly in line with the project!
Looking forward to reviewing it.
Current deployment is unwieldy and Docker was posited as the solution.

I'll be taking a deeper look at this Sunday.

A point of exploration will be `python -m app.utils.db.actions.full_build` - as that does nuke pre-existing tables.

Simplifying the admin docs around the Docker solution will be a next step too.

**Comment by mosajjal** [comment]
thanks for confirming. if that's the case, I'll move it to draft and do a bit more cleaning up and checks and balances here and there before putting it up for review. currently it's mvp-level.

**Comment by damionmounts** [comment]
Planning to dive-in tonight and see what I can do around:
- Existing database files -vs- none
- Exporting JSONs using the database interaction scripts **\***
- Bringing your own JSONs for building the database **\***

**\*** Thinking of a mounted volume for the app as well. So input/output jsons for the database interaction scripts can easily be accessed.

**Comment by damionmounts** [comment]
Oh sweet - I did that right.
First time I've ever needed to push to a contributor's PR.

Still sorting out this lovely bit of spam:
(may relate to healthcheck's command not specifying a user)
image

That and I'll be addressing the ToDos.

**Pull request merged**
